# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/.Xil/Vivado-29112-Star-TB14plus/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg484-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/modules/arithmetic_logic_unit/alu_compute_unit.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/constants/alu_constants.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/modules/arithmetic_logic_unit/alu_input_mux.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/modules/arithmetic_logic_unit/arithmetic_logic_unit.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/modules/branch.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/stages/execute.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/modules/instruction_decoder/instr_B_type.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/modules/instruction_decoder/instr_I_type.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/modules/instruction_decoder/instr_J_type.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/modules/instruction_decoder/instr_R_type.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/modules/instruction_decoder/instr_S_type.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/modules/instruction_decoder/instr_U_type.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/stages/instruction_decode.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/modules/instruction_decoder/instruction_decoder.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/stages/instruction_fetch.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/constants/memory_constants.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/modules/memory_controller.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/stages/memory_operation.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/modules/pc_adder.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/constants/pc_constants.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/modules/program_counter.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/modules/registers.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/constants/wb_constants.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/stages/write_back.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/modules/write_back_unit.v
      d:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/user/src/core/cpu_core.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top cpu_core
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/MyDocs/Codes/Embedded_FPGA/ADDL_RISCV_CPU/.Xil/Vivado-29112-Star-TB14plus/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
