`ifndef MEMORY_SELECT_V
`define MEMORY_SELECT_V

`define MEM_SEL_BYTE_SIGNED 3'b000
`define MEM_SEL_BYTE_UNSIGNED 3'b100
`define MEM_SEL_HALF_SIGNED 3'b001
`define MEM_SEL_HALF_UNSIGNED 3'b101
`define MEM_SEL_WORD 3'b010
`define MEM_SEL_NOP 3'b111 

`endif